[package]
name = "transform_console_write"
version = "0.1.0"
edition = "2024"

[dependencies]
rhexis-core = { path = "../../../rhexis-core" }
serde_cbor.workspace = true
serde.workspace = true


[lib]
crate-type = ["cdylib"]