[package]
name = "transform_rhex_summarize"
version = "0.1.0"
edition = "2024"

[dependencies]
rhexis-core = { path = "../../../rhexis-core" }
serde_cbor.workspace = true
serde_json.workspace = true
base64.workspace = true
hex.workspace = true

[lib]
crate-type = [ "cdylib" ]