[package]
name = "transform_lattice_scope_cache_store"
version = "0.1.0"
edition = "2024"

[dependencies]
rhexis-core = { path = "../../../rhexis-core" }
struct_lattice = { path = "../../struct/struct_lattice" }
struct_registry = { path = "../../struct/struct_registry" }
serde_cbor.workspace = true
serde_json.workspace = true
rand.workspace = true
hex.workspace = true

[lib]
crate-type = [ "cdylib" ]