[package]
name = "transform_lattice_usher_builder"
version = "0.1.0"
edition = "2024"

[dependencies]
rhexis-core = { path = "../../../rhexis-core" }
struct_lattice = { path = "../../struct/struct_lattice" }
serde_cbor.workspace = true
serde_json.workspace = true
hex.workspace = true
base64.workspace = true

[lib]
crate-type = [ "cdylib" ]