[package]
name = "transform_data_put-macos_arm64-v1"
version = "0.1.0"
edition = "2024"

[dependencies]
rhexis-core = { path = "../../../rhexis-core" }
hex.workspace = true
serde_json.workspace = true
serde_cbor.workspace = true

[lib]
crate-type = ["cdylib"]