[package]
name = "transform_data_put"
version = "0.2.0"
edition = "2024"

[dependencies]
rhexis-core = { path = "../../../rhexis-core" }
serde_cbor.workspace = true
serde_json.workspace = true
serde.workspace = true
hex.workspace = true

[lib]
crate-type = [ "cdylib" ]