[package]
name = "struct_net"
version = "0.1.0"
edition = "2024"

[dependencies]
rhexis-core = { path = "../../../rhexis-core" }
serde.workspace = true
serde_cbor.workspace = true
blake3.workspace = true
serde_bytes.workspace = true