[package]
name = "struct_registry"
version = "0.1.0"
edition = "2024"

[dependencies]
rhexis-core = { path = "../../../rhexis-core" }
serde.workspace = true
serde_cbor.workspace = true
serde_json.workspace = true
hex.workspace = true
