[package]
name = "rhexis-startup"
version = "0.1.0"
edition = "2024"

[dependencies]
rhexis-membrane = { path = "../rhexis-membrane" }
rhexis-core = { path = "../rhexis-core" }
clap.workspace = true
serde_json.workspace = true
serde_cbor.workspace = true