[package]
name = "transform_system_registry_result"
version = "0.1.0"
edition = "2024"

[dependencies]
rhexis-core = { path = "../../../rhexis-core" }
struct_registry = { path = "../../struct/struct_registry" }
serde_cbor.workspace = true
serde_json.workspace = true
hex.workspace = true
anyhow.workspace = true


[lib]
crate-type = [ "cdylib" ]