[package]
name = "hpc_crypto_ed25519_generate-macos_arm64-v1"
version = "0.1.0"
edition = "2024"

[dependencies]
rhexis-core = { path = "../../../rhexis-core" }
ed25519-dalek.workspace = true
serde.workspace = true
serde_cbor.workspace = true
rand.workspace = true
hex.workspace = true
rand_core.workspace = true

[lib]
crate-type = [ "cdylib" ]